spring:
  application:
    name: server-a
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8001
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
