spring:
  application:
    name: oauth-security

server:
  port: 9000


swagger2:
  version: 1.0
  resources:
  - name: SERVER_A (模块A)
    location: /server-a
  - name: DEMO_SERVER_B (模块B)
    location: /server-b
  - name: DEMO_SERVER_C (模块C)
    location: /server-c

info:
  desc: 集成了 SpringBootAdmin 和 Swagger2 ui
  swagger2-ui: http://localhost:9000/swagger-ui.html