spring:
  application:
    name: springboot-admin
server:
  port: 9000


swagger2:
  suffix: /v2/api-docs
  resources:
  - name: GateWay (网关)
    location: ${swagger2.suffix}
    version: v3
  - name: SERVER_A (模块A)
    location: /server/a
    version: 1.0
  - name: SERVER_B (模块B)
    location: /server/a
    version: 1.0
  - name: SERVER_C (模块C)
    location: /server/a
    version: 1.0