server:
  port: 9200


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: servera
        uri: lb://SERVER-A/
        filters:
        - StripPrefix=2
        predicates:
        - Path=/server/a/**

      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

